services:
  courses-ros2-concepts-l1:
    image: kalmanrobotics/courses:ros2-concepts-l1
    container_name: cont-courses-ros2-concepts-l1
    privileged: true
    command: sleep infinity
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/kalman/.Xauthority:rw
      - ./student:/kalman_ws/src:rw

    network_mode: "host"
